### ISSUE TITLE
about the interaction score

### ISSUE THREAD

**Issue by KivsenTrprio** [dgidb/dgidb#571]
Hello ,I have noticed that you have upgraded a lot in DGIdb3.0.I want to learn more details about how to calculate the interaction score, and what does this metric mean when I use it in comparing two pairs of interactions. For example, gene CDK7 and drug SELICICLIB held 0.87 interaction score while CDK7 and BMS-387032 held 0.82,does that mean  BMS-387032 is more powerful on 
influencing CDK7 gene? And ,one more thing ,could you give me some suggestions about how to recognize none DGI pairs which means there is no interactions between a certain gene and a certain drug.

**Comment by susannasiebert** [comment]
Thank you for your interest in DGIdb.

The interaction score represent the amount of support for a given interaction from the sources and publications present in DGIdb. It also takes into account relative drug and gene specificity and reduces the interaction score for drugs/genes that have many interaction records and are, therefore, not very specific to the drug-gene interaction in question. For a more thorough explanation, please see our [documentation](https://dgidb.org/score). You might also find the appropriate section in our [update paper](https://doi.org/10.1093/nar/gkaa1084) of help.

A drug that has no interaction records with a searched gene will not appear in the search result table for that gene and vice versa. Unfortunately, there isn't a more direct way to search for interactions of a specific gene with a specific drug but this might be something we can consider adding in future versions.
