### ISSUE TITLE
Filtering by interaction sources not working

### ISSUE THREAD

**Issue by cgrisdale** [dgidb/dgidb#587]
When trying to select interactions from specific sources I noticed interactions being returned that did not include my source of interest.

For example, this search returns several interactions from CIViC or CIVIC in combination with another source:
`https://dgidb.org/api/v2/interactions.json?genes=NRG1&nteraction_sources=CIViC`

but it also returns interactions where the only source is something other than 'CIViC', eg:
`{"interactionId":"eedbf74d-7e4b-4472-965e-87fe21d01261","interactionTypes":[],"drugName":"TAMOXIFEN","drugConceptId":"chembl:CHEMBL83","sources":["NCI"],"pmids":[18283314],"score":0.09}`

**Comment by nairod2000** [comment]
I believe this is due to a typo in the query parameters. Switching `nteraction_sources=CIViC` to `interaction_sources=CIViC` fixes the problem for me. The example query in the docs for the api has this same typo.
